openapi: 3.2.0
info:
  title: Identity Exposure SAML configuration API
  description: API to interact with Identity Exposure.
  version: production
servers:
- url: '{protocol}://customer.tenable.ad'
  variables:
    protocol:
      default: https
tags:
- name: SAML Configuration
  description: Authentification configuration with SAML
paths:
  /api/saml-configuration:
    get:
      summary: Get saml-configuration singleton
      description: 'Required license type: ioa, ioaPreview, ioe'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                additionalProperties: false
                required:
                - enabled
                - providerLoginUrl
                - encryptionCertificate
                - signatureCertificate
                - serviceProviderUrl
                - assertEndpoint
                - activateCreatedUsers
                - allowedGroups
                properties:
                  enabled:
                    type: boolean
                  providerLoginUrl:
                    type:
                    - string
                    - 'null'
                  encryptionCertificate:
                    type:
                    - string
                    - 'null'
                  signatureCertificate:
                    type:
                    - string
                    - 'null'
                  serviceProviderUrl:
                    type:
                    - string
                    - 'null'
                  assertEndpoint:
                    type:
                    - string
                    - 'null'
                  activateCreatedUsers:
                    type: boolean
                  allowedGroups:
                    type:
                    - array
                    - 'null'
                    items:
                      type: object
                      additionalProperties: false
                      properties:
                        name:
                          type: string
                        defaultProfileId:
                          type: integer
                        defaultRoleIds:
                          type: array
                          items:
                            type: integer
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      tags:
      - SAML Configuration
      x-tenablead-required-product-license-type:
      - ioa
      - ioaPreview
      - ioe
      parameters:
      - name: x-api-key
        description: The user's API key
        in: header
        schema:
          type: string
          default: put-your-api-key-here
        required: true
        deprecated: false
      security:
      - ApiKey: []
      operationId: getApiSamlConfiguration
      x-operation-id-source: derived
    patch:
      summary: Update saml-configuration singleton
      description: 'Required license type: ioa, ioaPreview, ioe'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                additionalProperties: false
                required:
                - enabled
                - providerLoginUrl
                - encryptionCertificate
                - signatureCertificate
                - serviceProviderUrl
                - assertEndpoint
                - activateCreatedUsers
                - allowedGroups
                properties:
                  enabled:
                    type: boolean
                  providerLoginUrl:
                    type:
                    - string
                    - 'null'
                  encryptionCertificate:
                    type:
                    - string
                    - 'null'
                  signatureCertificate:
                    type:
                    - string
                    - 'null'
                  serviceProviderUrl:
                    type:
                    - string
                    - 'null'
                  assertEndpoint:
                    type:
                    - string
                    - 'null'
                  activateCreatedUsers:
                    type: boolean
                  allowedGroups:
                    type:
                    - array
                    - 'null'
                    items:
                      type: object
                      additionalProperties: false
                      properties:
                        name:
                          type: string
                        defaultProfileId:
                          type: integer
                        defaultRoleIds:
                          type: array
                          items:
                            type: integer
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      tags:
      - SAML Configuration
      x-tenablead-required-product-license-type:
      - ioa
      - ioaPreview
      - ioe
      parameters:
      - name: x-api-key
        description: The user's API key
        in: header
        schema:
          type: string
          default: put-your-api-key-here
        required: true
        deprecated: false
      security:
      - ApiKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                enabled:
                  type: boolean
                providerLoginUrl:
                  type:
                  - string
                  - 'null'
                signatureCertificate:
                  type:
                  - string
                  - 'null'
                activateCreatedUsers:
                  type: boolean
                allowedGroups:
                  type:
                  - array
                  - 'null'
                  minItems: 1
                  items:
                    type: object
                    required:
                    - name
                    - defaultRoleIds
                    - defaultProfileId
                    additionalProperties: false
                    properties:
                      name:
                        type: string
                      defaultProfileId:
                        type: integer
                      defaultRoleIds:
                        type: array
                        items:
                          type: integer
      operationId: patchApiSamlConfiguration
      x-operation-id-source: derived
  /api/saml-configuration/generate-certificate:
    get:
      summary: Generates SAML certificate
      description: 'Required license type: ioa, ioaPreview, ioe'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                required:
                - encryptionCertificate
                properties:
                  encryptionCertificate:
                    type: string
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      tags:
      - SAML Configuration
      x-tenablead-required-product-license-type:
      - ioa
      - ioaPreview
      - ioe
      parameters:
      - name: x-api-key
        description: The user's API key
        in: header
        schema:
          type: string
          default: put-your-api-key-here
        required: true
        deprecated: false
      security:
      - ApiKey: []
      operationId: getApiSamlConfigurationGenerateCertificate
      x-operation-id-source: derived
components:
  securitySchemes:
    ApiKey:
      name: x-api-key
      description: The user's API key
      in: header
      type: apiKey
x-readme:
  explorer-enabled: true
  proxy-enabled: true
