openapi: 3.2.0
info:
  title: Identity Exposure Score API
  description: API to interact with Identity Exposure.
  version: production
servers:
- url: '{protocol}://customer.tenable.ad'
  variables:
    protocol:
      default: https
tags:
- name: Score
  description: The directories' scores
paths:
  /api/profiles/{profileId}/scores:
    get:
      summary: Get the directories score by profile
      description: 'Required license type: ioe'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                description: Directories' scores
                type: array
                additionalProperties: false
                items:
                  type: object
                  additionalProperties: false
                  required:
                  - directoryId
                  - score
                  properties:
                    directoryId:
                      type: number
                    score:
                      type:
                      - number
                      - 'null'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      tags:
      - Score
      x-tenablead-required-product-license-type:
      - ioe
      parameters:
      - name: x-api-key
        description: The user's API key
        in: header
        schema:
          type: string
          default: put-your-api-key-here
        required: true
        deprecated: false
      - name: profileId
        in: path
        schema:
          type: string
          pattern: ^[0-9]+$
          x-patternError: should be a numerical string
        required: true
        deprecated: false
      - name: directoryIds
        in: query
        schema:
          description: Directory on which to calculate score
          oneOf:
          - type: array
            items:
              type: string
              pattern: ^[0-9]+$
              x-patternError: should be a numerical string
          - type: string
            pattern: ^[0-9]+$
            x-patternError: should be a numerical string
        required: false
        deprecated: false
      - name: checkerIds
        in: query
        schema:
          description: IOE to filter on each directory in score calculation
          oneOf:
          - type: array
            items:
              type: string
              pattern: ^[0-9]+$
              x-patternError: should be a numerical string
          - type: string
            pattern: ^[0-9]+$
            x-patternError: should be a numerical string
        required: false
        deprecated: false
      - name: reasonIds
        in: query
        schema:
          description: IOE reason to filter on each directory in score calculation
          oneOf:
          - type: array
            items:
              type: string
              pattern: ^[0-9]+$
              x-patternError: should be a numerical string
          - type: string
            pattern: ^[0-9]+$
            x-patternError: should be a numerical string
        required: false
        deprecated: false
      security:
      - ApiKey: []
      operationId: getApiProfilesByProfileIdScores
      x-operation-id-source: derived
components:
  securitySchemes:
    ApiKey:
      name: x-api-key
      description: The user's API key
      in: header
      type: apiKey
x-readme:
  explorer-enabled: true
  proxy-enabled: true
