openapi: 3.2.0
info:
  title: Identity Exposure About API
  description: API to interact with Identity Exposure.
  version: production
servers:
- url: '{protocol}://customer.tenable.ad'
  variables:
    protocol:
      default: https
tags:
- name: About
  description: Provide general information on Eridanis
paths:
  /api/about:
    get:
      summary: Get about singleton
      description: 'Required license type: none'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                required:
                - version
                - isSaaSDeployment
                properties:
                  version:
                    type: string
                  hostname:
                    type: string
                  isSaaSDeployment:
                    type: boolean
        '500':
          description: Internal server error
      tags:
      - About
      x-tenablead-required-product-license-type: []
      operationId: getApiAbout
      x-operation-id-source: derived
components:
  securitySchemes:
    ApiKey:
      name: x-api-key
      description: The user's API key
      in: header
      type: apiKey
x-readme:
  explorer-enabled: true
  proxy-enabled: true
