openapi: 3.2.0
info:
  title: Identity Exposure Application setting API
  description: API to interact with Identity Exposure.
  version: production
servers:
- url: '{protocol}://customer.tenable.ad'
  variables:
    protocol:
      default: https
tags:
- name: Application setting
  description: Tenable.ad global configuration
paths:
  /api/application-settings:
    get:
      summary: Get the application settings
      description: 'Required license type: ioa, ioaPreview, ioe'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                description: Validates the GET /application-settings response payload
                type: object
                additionalProperties: false
                required:
                - userRegistration
                - activityLogsIsActive
                - activityLogsRetentionDurationInMonth
                - smtpServerAddress
                - smtpServerPort
                - smtpAccount
                - smtpAccountPassword
                - smtpUseStartTLS
                - tls
                - emailSender
                - defaultProfileId
                - defaultRoleIds
                - internalCertificate
                - telemetryEnabled
                - ioaAutomaticConfiguration
                - cloudStatisticsIsActive
                - healthCheckGlobalStatusDisplayEnabled
                properties:
                  userRegistration:
                    type: boolean
                  activityLogsIsActive:
                    type: boolean
                  activityLogsRetentionDurationInMonth:
                    type: integer
                    enum:
                    - 1
                    - 2
                    - 3
                    - 4
                    - 5
                    - 6
                  smtpServerAddress:
                    type:
                    - string
                    - 'null'
                  smtpServerPort:
                    type:
                    - number
                    - 'null'
                  smtpAccount:
                    type:
                    - string
                    - 'null'
                  smtpAccountPassword:
                    type:
                    - string
                    - 'null'
                    x-secret: true
                  smtpUseStartTLS:
                    type: boolean
                  smtpRelayId:
                    type:
                    - number
                    - 'null'
                  tls:
                    type: boolean
                  emailSender:
                    type: string
                  defaultRoleIds:
                    type: array
                    items:
                      type: integer
                  defaultProfileId:
                    type: integer
                  internalCertificate:
                    type:
                    - string
                    - 'null'
                  telemetryEnabled:
                    type: boolean
                  ioaAutomaticConfiguration:
                    type: boolean
                  cloudStatisticsIsActive:
                    type: boolean
                  healthCheckGlobalStatusDisplayEnabled:
                    type: boolean
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      tags:
      - Application setting
      x-tenablead-required-product-license-type:
      - ioa
      - ioaPreview
      - ioe
      parameters:
      - name: x-api-key
        description: The user's API key
        in: header
        schema:
          type: string
          default: put-your-api-key-here
        required: true
        deprecated: false
      security:
      - ApiKey: []
      operationId: getApiApplicationSettings
      x-operation-id-source: derived
    patch:
      summary: Update the application settings
      description: 'Required license type: ioa, ioaPreview, ioe'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                description: Validates the PATCH /application-settings response payload
                type: object
                additionalProperties: false
                required:
                - userRegistration
                - activityLogsIsActive
                - activityLogsRetentionDurationInMonth
                - smtpServerAddress
                - smtpServerPort
                - smtpAccount
                - smtpAccountPassword
                - smtpUseStartTLS
                - tls
                - emailSender
                - defaultProfileId
                - defaultRoleIds
                - internalCertificate
                - telemetryEnabled
                - ioaAutomaticConfiguration
                - cloudStatisticsIsActive
                - healthCheckGlobalStatusDisplayEnabled
                properties:
                  userRegistration:
                    type: boolean
                  activityLogsIsActive:
                    type: boolean
                  activityLogsRetentionDurationInMonth:
                    type: integer
                    enum:
                    - 1
                    - 2
                    - 3
                    - 4
                    - 5
                    - 6
                  smtpServerAddress:
                    type:
                    - string
                    - 'null'
                  smtpServerPort:
                    type:
                    - number
                    - 'null'
                  smtpAccount:
                    type:
                    - string
                    - 'null'
                  smtpAccountPassword:
                    type:
                    - string
                    - 'null'
                    x-secret: true
                  smtpUseStartTLS:
                    type: boolean
                  smtpRelayId:
                    type:
                    - number
                    - 'null'
                  tls:
                    type: boolean
                  emailSender:
                    type: string
                  defaultRoleIds:
                    type: array
                    items:
                      type: integer
                  defaultProfileId:
                    type: integer
                  internalCertificate:
                    type:
                    - string
                    - 'null'
                  telemetryEnabled:
                    type: boolean
                  ioaAutomaticConfiguration:
                    type: boolean
                  cloudStatisticsIsActive:
                    type: boolean
                  healthCheckGlobalStatusDisplayEnabled:
                    type: boolean
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      tags:
      - Application setting
      x-tenablead-required-product-license-type:
      - ioa
      - ioaPreview
      - ioe
      parameters:
      - name: x-api-key
        description: The user's API key
        in: header
        schema:
          type: string
          default: put-your-api-key-here
        required: true
        deprecated: false
      security:
      - ApiKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: Application settings
              type: object
              additionalProperties: false
              properties:
                userRegistration:
                  type: boolean
                activityLogsIsActive:
                  type: boolean
                activityLogsRetentionDurationInMonth:
                  type:
                  - integer
                  - 'null'
                  enum:
                  - 1
                  - 2
                  - 3
                  - 4
                  - 5
                  - 6
                smtpServerAddress:
                  type:
                  - string
                  - 'null'
                smtpServerPort:
                  type:
                  - integer
                  - 'null'
                smtpAccount:
                  type:
                  - string
                  - 'null'
                smtpAccountPassword:
                  type:
                  - string
                  - 'null'
                  x-secret: true
                smtpUseStartTLS:
                  type: boolean
                smtpRelayId:
                  type:
                  - number
                  - 'null'
                tls:
                  type: boolean
                emailSender:
                  type: string
                defaultRoleIds:
                  type: array
                  items:
                    type: integer
                defaultProfileId:
                  type: integer
                internalCertificate:
                  type:
                  - string
                  - 'null'
                telemetryEnabled:
                  type: boolean
                ioaAutomaticConfiguration:
                  type: boolean
                cloudStatisticsIsActive:
                  type: boolean
                healthCheckGlobalStatusDisplayEnabled:
                  type: boolean
      operationId: patchApiApplicationSettings
      x-operation-id-source: derived
components:
  securitySchemes:
    ApiKey:
      name: x-api-key
      description: The user's API key
      in: header
      type: apiKey
x-readme:
  explorer-enabled: true
  proxy-enabled: true
