openapi: 3.2.0
info:
  title: Identity Exposure Attack type configuration API
  description: API to interact with Identity Exposure.
  version: production
servers:
- url: '{protocol}://customer.tenable.ad'
  variables:
    protocol:
      default: https
tags:
- name: Attack type configuration
  description: The attack type per directory configuration
paths:
  /api/attack-type-configuration:
    get:
      summary: Get the attack type configuration
      description: 'Required license type: ioa, ioaPreview'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                description: Response payload of the GET /attack-type-configuration route
                type: object
                additionalProperties: false
                required:
                - version
                - configuration
                - permissions
                properties:
                  version:
                    type: integer
                  configuration:
                    type: array
                    items:
                      type: object
                      required:
                      - attackTypeId
                      - directoryId
                      - detectedEvents
                      - autoDisabledForPerfAt
                      properties:
                        attackTypeId:
                          type: integer
                        directoryId:
                          type: integer
                        detectedEvents:
                          type: boolean
                        autoDisabledForPerfAt:
                          type:
                          - string
                          - 'null'
                          format: date-time
                  permissions:
                    type: object
                    properties:
                      canEdit:
                        type: boolean
                    required:
                    - canEdit
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      tags:
      - Attack type configuration
      x-tenablead-required-product-license-type:
      - ioa
      - ioaPreview
      parameters:
      - name: x-api-key
        description: The user's API key
        in: header
        schema:
          type: string
          default: put-your-api-key-here
        required: true
        deprecated: false
      security:
      - ApiKey: []
      operationId: getApiAttackTypeConfiguration
      x-operation-id-source: derived
    patch:
      summary: Update the attack type configuration
      description: 'Required license type: ioa, ioaPreview'
      responses:
        '204':
          description: ''
          content:
            application/json:
              schema:
                description: Validates the patch /attack-type-configuration response
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      tags:
      - Attack type configuration
      x-tenablead-required-product-license-type:
      - ioa
      - ioaPreview
      parameters:
      - name: x-api-key
        description: The user's API key
        in: header
        schema:
          type: string
          default: put-your-api-key-here
        required: true
        deprecated: false
      security:
      - ApiKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: Validates the patch /attack-type-configuration payload
              type: object
              additionalProperties: false
              properties:
                configuration:
                  type: array
                  items:
                    type: object
                    required:
                    - attackTypeId
                    - directoryId
                    properties:
                      attackTypeId:
                        type: integer
                      directoryId:
                        type: integer
      operationId: patchApiAttackTypeConfiguration
      x-operation-id-source: derived
components:
  securitySchemes:
    ApiKey:
      name: x-api-key
      description: The user's API key
      in: header
      type: apiKey
x-readme:
  explorer-enabled: true
  proxy-enabled: true
