openapi: 3.2.0
info:
  title: Identity Exposure Metrics API
  description: API to interact with Identity Exposure.
  version: production
servers:
- url: '{protocol}://customer.tenable.ad'
  variables:
    protocol:
      default: https
tags:
- name: Metrics
paths:
  /api/metrics:
    get:
      summary: Collect Eridanis and SQL Server health metrics
      description: 'Required license type: none'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Internal server error
      tags:
      - Metrics
      x-tenablead-required-product-license-type: []
      operationId: getApiMetrics
      x-operation-id-source: derived
components:
  securitySchemes:
    ApiKey:
      name: x-api-key
      description: The user's API key
      in: header
      type: apiKey
x-readme:
  explorer-enabled: true
  proxy-enabled: true
