openapi: 3.2.0
info:
  title: Identity Exposure Preference API
  description: API to interact with Identity Exposure.
  version: production
servers:
- url: '{protocol}://customer.tenable.ad'
  variables:
    protocol:
      default: https
tags:
- name: Preference
  description: A user's preferences
paths:
  /api/preferences:
    get:
      summary: Get a user's preferences
      description: 'Required license type: none'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                description: Preference
                type: object
                additionalProperties: false
                required:
                - language
                - preferredProfileId
                properties:
                  language:
                    type: string
                  preferredProfileId:
                    type: integer
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      tags:
      - Preference
      x-tenablead-required-product-license-type: []
      parameters:
      - name: x-api-key
        description: The user's API key
        in: header
        schema:
          type: string
          default: put-your-api-key-here
        required: true
        deprecated: false
      security:
      - ApiKey: []
      operationId: getApiPreferences
      x-operation-id-source: derived
    patch:
      summary: Update a user's preferences
      description: 'Required license type: none'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                description: Preference
                type: object
                additionalProperties: false
                required:
                - language
                - preferredProfileId
                properties:
                  language:
                    type: string
                  preferredProfileId:
                    type: integer
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      tags:
      - Preference
      x-tenablead-required-product-license-type: []
      parameters:
      - name: x-api-key
        description: The user's API key
        in: header
        schema:
          type: string
          default: put-your-api-key-here
        required: true
        deprecated: false
      security:
      - ApiKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: Preference
              type: object
              additionalProperties: false
              properties:
                language:
                  type: string
                preferredProfileId:
                  type: integer
      operationId: patchApiPreferences
      x-operation-id-source: derived
components:
  securitySchemes:
    ApiKey:
      name: x-api-key
      description: The user's API key
      in: header
      type: apiKey
x-readme:
  explorer-enabled: true
  proxy-enabled: true
