openapi: 3.2.0
info:
  title: Identity Exposure API key API
  description: API to interact with Identity Exposure.
  version: production
servers:
- url: '{protocol}://customer.tenable.ad'
  variables:
    protocol:
      default: https
tags:
- name: API Key
  description: Token to programmatically access Eridanis
paths:
  /api/api-key:
    get:
      summary: Get the API key of the current user
      description: 'Required license type: ioa, ioaPreview, ioe'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                description: Validates GET /api-key responses
                type: object
                additionalProperties: false
                required:
                - key
                properties:
                  key:
                    type: string
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      tags:
      - API Key
      x-tenablead-required-product-license-type:
      - ioa
      - ioaPreview
      - ioe
      parameters:
      - name: x-api-key
        description: The user's API key
        in: header
        schema:
          type: string
          default: put-your-api-key-here
        required: true
        deprecated: false
      security:
      - ApiKey: []
      operationId: getApiApiKey
      x-operation-id-source: derived
    post:
      summary: Create or renew an API key for the current user
      description: 'Required license type: ioa, ioaPreview, ioe'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                description: Validates POST /api-key responses
                type: object
                additionalProperties: false
                required:
                - key
                properties:
                  key:
                    type: string
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      tags:
      - API Key
      x-tenablead-required-product-license-type:
      - ioa
      - ioaPreview
      - ioe
      parameters:
      - name: x-api-key
        description: The user's API key
        in: header
        schema:
          type: string
          default: put-your-api-key-here
        required: true
        deprecated: false
      security:
      - ApiKey: []
      operationId: postApiApiKey
      x-operation-id-source: derived
components:
  securitySchemes:
    ApiKey:
      name: x-api-key
      description: The user's API key
      in: header
      type: apiKey
x-readme:
  explorer-enabled: true
  proxy-enabled: true
