openapi: 3.2.0
info:
  title: Identity Exposure Alert API
  description: API to interact with Identity Exposure.
  version: production
servers:
- url: '{protocol}://customer.tenable.ad'
  variables:
    protocol:
      default: https
tags:
- name: Alert
  description: New deviances alert
paths:
  /api/alerts/{id}:
    get:
      summary: Get alert instance by id
      description: 'Required license type: ioe, ioaPreview, ioa'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                description: Alert
                type: object
                additionalProperties: false
                required:
                - id
                - devianceId
                - archived
                - read
                - date
                - directoryId
                - infrastructureId
                properties:
                  id:
                    type: integer
                  devianceId:
                    type: integer
                  archived:
                    type: boolean
                    default: false
                  read:
                    type: boolean
                    default: false
                  date:
                    type: string
                    format: date-time
                  directoryId:
                    type: integer
                  infrastructureId:
                    type: integer
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      tags:
      - Alert
      x-tenablead-required-product-license-type:
      - ioe
      - ioaPreview
      - ioa
      parameters:
      - name: x-api-key
        description: The user's API key
        in: header
        schema:
          type: string
          default: put-your-api-key-here
        required: true
        deprecated: false
      - name: id
        in: path
        schema:
          type: string
          pattern: ^[0-9]+$
          x-patternError: should be a numerical string
        required: true
        deprecated: false
      security:
      - ApiKey: []
      operationId: getApiAlertsById
      x-operation-id-source: derived
    patch:
      summary: Update alert instance
      description: 'Required license type: ioe, ioaPreview, ioa'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                description: Alert
                type: object
                additionalProperties: false
                required:
                - id
                - devianceId
                - archived
                - read
                - date
                - directoryId
                - infrastructureId
                properties:
                  id:
                    type: integer
                  devianceId:
                    type: integer
                  archived:
                    type: boolean
                    default: false
                  read:
                    type: boolean
                    default: false
                  date:
                    type: string
                    format: date-time
                  directoryId:
                    type: integer
                  infrastructureId:
                    type: integer
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      tags:
      - Alert
      x-tenablead-required-product-license-type:
      - ioe
      - ioaPreview
      - ioa
      parameters:
      - name: x-api-key
        description: The user's API key
        in: header
        schema:
          type: string
          default: put-your-api-key-here
        required: true
        deprecated: false
      - name: id
        in: path
        schema:
          type: string
          pattern: ^[0-9]+$
          x-patternError: should be a numerical string
        required: true
        deprecated: false
      security:
      - ApiKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: Validates the PATCH /alerts/:id request
              type: object
              additionalProperties: false
              properties:
                archived:
                  type: boolean
                read:
                  type: boolean
      operationId: patchApiAlertsById
      x-operation-id-source: derived
  /api/profiles/{profileId}/alerts:
    get:
      summary: Retrieve all alert instances
      description: 'Required license type: ioe, ioaPreview, ioa'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                description: Validates the GET /alert response
                type: array
                items:
                  description: Alert
                  type: object
                  additionalProperties: false
                  required:
                  - id
                  - devianceId
                  - archived
                  - read
                  - date
                  - directoryId
                  - infrastructureId
                  properties:
                    id:
                      type: integer
                    devianceId:
                      type: integer
                    archived:
                      type: boolean
                      default: false
                    read:
                      type: boolean
                      default: false
                    date:
                      type: string
                      format: date-time
                    directoryId:
                      type: integer
                    infrastructureId:
                      type: integer
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      tags:
      - Alert
      x-tenablead-required-product-license-type:
      - ioe
      - ioaPreview
      - ioa
      parameters:
      - name: x-api-key
        description: The user's API key
        in: header
        schema:
          type: string
          default: put-your-api-key-here
        required: true
        deprecated: false
      - name: profileId
        in: path
        schema:
          type: string
          pattern: ^[0-9]+$
          x-patternError: should be a numerical string
        required: true
        deprecated: false
      - name: archived
        in: query
        schema:
          type: string
          enum:
          - 'true'
          - 'false'
        required: false
        deprecated: false
      - name: read
        in: query
        schema:
          type: string
          enum:
          - 'true'
          - 'false'
        required: false
        deprecated: false
      - name: perPage
        in: query
        schema:
          type: string
          pattern: ^[0-9]+$
          x-patternError: should be a numerical string
        required: false
        deprecated: false
      - name: page
        in: query
        schema:
          type: string
          pattern: ^[0-9]+$
          x-patternError: should be a numerical string
        required: false
        deprecated: false
      security:
      - ApiKey: []
      operationId: getApiProfilesByProfileIdAlerts
      x-operation-id-source: derived
    patch:
      summary: Update alerts for one profile
      description: 'Required license type: ioe, ioaPreview, ioa'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                description: Alert
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      tags:
      - Alert
      x-tenablead-required-product-license-type:
      - ioe
      - ioaPreview
      - ioa
      parameters:
      - name: x-api-key
        description: The user's API key
        in: header
        schema:
          type: string
          default: put-your-api-key-here
        required: true
        deprecated: false
      - name: profileId
        in: path
        schema:
          type: string
          pattern: ^[0-9]+$
          x-patternError: should be a numerical string
        required: true
        deprecated: false
      security:
      - ApiKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: Validates the PATCH /alerts request
              type: object
              additionalProperties: false
              properties:
                archived:
                  type: boolean
                read:
                  type: boolean
      operationId: patchApiProfilesByProfileIdAlerts
      x-operation-id-source: derived
components:
  securitySchemes:
    ApiKey:
      name: x-api-key
      description: The user's API key
      in: header
      type: apiKey
x-readme:
  explorer-enabled: true
  proxy-enabled: true
