openapi: 3.2.0
info:
  title: Identity Exposure Lockout policy API
  description: API to interact with Identity Exposure.
  version: production
servers:
- url: '{protocol}://customer.tenable.ad'
  variables:
    protocol:
      default: https
tags:
- name: Lockout Policy
  description: Configuration of the mechanism that locks out user accounts after multiple failed login attempts.
paths:
  /api/lockout-policy:
    get:
      summary: Get the lockout policy
      description: 'Required license type: none'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                description: GET /lockout-policy response payload
                type: object
                additionalProperties: false
                required:
                - enabled
                - lockoutDuration
                - failedAttemptThreshold
                - failedAttemptPeriod
                properties:
                  enabled:
                    type: boolean
                  lockoutDuration:
                    type: integer
                    minimum: 0
                  failedAttemptThreshold:
                    type: integer
                    minimum: 1
                    maximum: 50
                  failedAttemptPeriod:
                    type: integer
                    minimum: 0
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      tags:
      - Lockout Policy
      x-tenablead-required-product-license-type: []
      parameters:
      - name: x-api-key
        description: The user's API key
        in: header
        schema:
          type: string
          default: put-your-api-key-here
        required: true
        deprecated: false
      security:
      - ApiKey: []
      operationId: getApiLockoutPolicy
      x-operation-id-source: derived
    patch:
      summary: Update the lockout policy
      description: 'Required license type: none'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                description: PATCH /lockout-policy response payload
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      tags:
      - Lockout Policy
      x-tenablead-required-product-license-type: []
      parameters:
      - name: x-api-key
        description: The user's API key
        in: header
        schema:
          type: string
          default: put-your-api-key-here
        required: true
        deprecated: false
      security:
      - ApiKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: PATCH /lockout-policy request payload
              type: object
              additionalProperties: false
              properties:
                enabled:
                  type: boolean
                lockoutDuration:
                  type: integer
                  minimum: 0
                failedAttemptThreshold:
                  type: integer
                  minimum: 1
                  maximum: 50
                failedAttemptPeriod:
                  type: integer
                  minimum: 0
      operationId: patchApiLockoutPolicy
      x-operation-id-source: derived
components:
  securitySchemes:
    ApiKey:
      name: x-api-key
      description: The user's API key
      in: header
      type: apiKey
x-readme:
  explorer-enabled: true
  proxy-enabled: true
