openapi: 3.2.0
info:
  title: Identity Exposure Checker API
  description: API to interact with Identity Exposure.
  version: production
servers:
- url: '{protocol}://customer.tenable.ad'
  variables:
    protocol:
      default: https
tags:
- name: Checker
  description: Checkers are the implementations of the state of the art of AD security
paths:
  /api/checkers:
    get:
      summary: Retrieve all checker instances
      description: 'Required license type: ioe'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                description: Validates the get /checkers response
                type: array
                items:
                  description: A checker instance
                  type: object
                  additionalProperties: false
                  required:
                  - id
                  - codename
                  - categoryId
                  - remediationCost
                  properties:
                    id:
                      type: number
                      description: ' Unique numeric identifier of the checker'
                    codename:
                      type: string
                      example: C-SAMPLE-DUMMY
                      description: ' Unique string identifier of the checker'
                    categoryId:
                      type: integer
                      description: Identifier of the category the checker belongs to
                    remediationCost:
                      type: integer
                      description: Remediation cost of the checker findings
                      deprecated: true
                    name:
                      type:
                      - string
                      - 'null'
                      default: null
                      description: Localized name of the checker
                    description:
                      type:
                      - string
                      - 'null'
                      default: null
                      description: Localized description of the checker
                    execSummary:
                      type:
                      - string
                      - 'null'
                      default: null
                      description: Localized executive summary of the checker findings
                    vulnerabilityDetail:
                      type: object
                      default: {}
                      properties:
                        detail:
                          type:
                          - string
                          - 'null'
                          default: null
                      description: Localized technical explanations on the checks performed by the checker
                    attackerKnownTools:
                      type: array
                      default: []
                      items:
                        type: object
                        properties:
                          name:
                            type:
                            - string
                            - 'null'
                            default: null
                          url:
                            type:
                            - string
                            - 'null'
                            default: null
                          author:
                            type:
                            - string
                            - 'null'
                            default: null
                      description: Known attacker tools that can exploit the vulnerabilities the checker looks for
                    resources:
                      type: array
                      default: []
                      items:
                        type: object
                        properties:
                          name:
                            type:
                            - string
                            - 'null'
                            default: null
                          url:
                            type:
                            - string
                            - 'null'
                            default: null
                          type:
                            type:
                            - string
                            - 'null'
                            default: null
                      description: Resources helping understand the vulnerabilities the checker looks for
                    recommendation:
                      type: object
                      default: {}
                      properties:
                        name:
                          type:
                          - string
                          - 'null'
                          default: null
                        description:
                          type:
                          - string
                          - 'null'
                          default: null
                        execSummary:
                          type:
                          - string
                          - 'null'
                          default: null
                        detail:
                          type:
                          - string
                          - 'null'
                          default: null
                        resources:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type:
                                - string
                                - 'null'
                                default: null
                              url:
                                type:
                                - string
                                - 'null'
                                default: null
                              type:
                                type:
                                - string
                                - 'null'
                                default: null
                      description: Recommendations on how to remediate the issues identified by the checker
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      tags:
      - Checker
      x-tenablead-required-product-license-type:
      - ioe
      parameters:
      - name: x-api-key
        description: The user's API key
        in: header
        schema:
          type: string
          default: put-your-api-key-here
        required: true
        deprecated: false
      security:
      - ApiKey: []
      operationId: getApiCheckers
      x-operation-id-source: derived
  /api/checkers/{id}:
    get:
      summary: Get checker instance by id
      description: 'Required license type: ioe'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                description: Checker
                type: object
                additionalProperties: false
                required:
                - id
                - codename
                - categoryId
                - remediationCost
                properties:
                  id:
                    type: number
                  codename:
                    type: string
                    example: C-toto-s
                  categoryId:
                    type: integer
                  remediationCost:
                    type: integer
                  name:
                    type:
                    - string
                    - 'null'
                    default: null
                  description:
                    type:
                    - string
                    - 'null'
                    default: null
                  execSummary:
                    type:
                    - string
                    - 'null'
                    default: null
                  vulnerabilityDetail:
                    type: object
                    default: {}
                    properties:
                      detail:
                        type:
                        - string
                        - 'null'
                        default: null
                  attackerKnownTools:
                    type: array
                    default: []
                    items:
                      type: object
                      properties:
                        name:
                          type:
                          - string
                          - 'null'
                          default: null
                        url:
                          type:
                          - string
                          - 'null'
                          default: null
                        author:
                          type:
                          - string
                          - 'null'
                          default: null
                  resources:
                    type: array
                    default: []
                    items:
                      type: object
                      properties:
                        name:
                          type:
                          - string
                          - 'null'
                          default: null
                        url:
                          type:
                          - string
                          - 'null'
                          default: null
                        type:
                          type:
                          - string
                          - 'null'
                          default: null
                  recommendation:
                    type: object
                    default: {}
                    properties:
                      name:
                        type:
                        - string
                        - 'null'
                        default: null
                      description:
                        type:
                        - string
                        - 'null'
                        default: null
                      execSummary:
                        type:
                        - string
                        - 'null'
                        default: null
                      detail:
                        type:
                        - string
                        - 'null'
                        default: null
                      resources:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type:
                              - string
                              - 'null'
                              default: null
                            url:
                              type:
                              - string
                              - 'null'
                              default: null
                            type:
                              type:
                              - string
                              - 'null'
                              default: null
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      tags:
      - Checker
      x-tenablead-required-product-license-type:
      - ioe
      parameters:
      - name: x-api-key
        description: The user's API key
        in: header
        schema:
          type: string
          default: put-your-api-key-here
        required: true
        deprecated: false
      - name: id
        in: path
        schema:
          type: string
          pattern: ^[0-9]+$
          x-patternError: should be a numerical string
        required: true
        deprecated: false
      security:
      - ApiKey: []
      operationId: getApiCheckersById
      x-operation-id-source: derived
components:
  securitySchemes:
    ApiKey:
      name: x-api-key
      description: The user's API key
      in: header
      type: apiKey
x-readme:
  explorer-enabled: true
  proxy-enabled: true
