openapi: 3.2.0
info:
  title: Identity Exposure LDAP configuration API
  description: API to interact with Identity Exposure.
  version: production
servers:
- url: '{protocol}://customer.tenable.ad'
  variables:
    protocol:
      default: https
tags:
- name: LDAP Configuration
  description: Configuration of LDAP for authentication purposes.
paths:
  /api/ldap-configuration:
    get:
      summary: Get ldap-configuration singleton
      description: 'Required license type: ioa, ioaPreview, ioe'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                required:
                - enabled
                - url
                - searchUserDN
                - searchUserPassword
                - userSearchBase
                - userSearchFilter
                - allowedGroups
                properties:
                  enabled:
                    type: boolean
                    default: 'false'
                  url:
                    type:
                    - string
                    - 'null'
                  searchUserDN:
                    type:
                    - string
                    - 'null'
                  searchUserPassword:
                    type:
                    - string
                    - 'null'
                  userSearchBase:
                    type:
                    - string
                    - 'null'
                  userSearchFilter:
                    type:
                    - string
                    - 'null'
                  allowedGroups:
                    type:
                    - array
                    - 'null'
                    items:
                      type: object
                      additionalProperties: false
                      properties:
                        name:
                          type: string
                        defaultRoleIds:
                          type: array
                          items:
                            type: integer
                        defaultProfileId:
                          type: integer
                  enableSaslBinding:
                    type: boolean
                  relayId:
                    type:
                    - number
                    - 'null'
                  relayUuid:
                    type:
                    - string
                    - 'null'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      tags:
      - LDAP Configuration
      x-tenablead-required-product-license-type:
      - ioa
      - ioaPreview
      - ioe
      parameters:
      - name: x-api-key
        description: The user's API key
        in: header
        schema:
          type: string
          default: put-your-api-key-here
        required: true
        deprecated: false
      security:
      - ApiKey: []
      operationId: getApiLdapConfiguration
      x-operation-id-source: derived
    patch:
      summary: Update ldap-configuration singleton
      description: 'Required license type: ioa, ioaPreview, ioe'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                required:
                - enabled
                - url
                - searchUserDN
                - searchUserPassword
                - userSearchBase
                - userSearchFilter
                - allowedGroups
                properties:
                  enabled:
                    type: boolean
                    default: 'false'
                  url:
                    type:
                    - string
                    - 'null'
                  searchUserDN:
                    type:
                    - string
                    - 'null'
                  searchUserPassword:
                    type:
                    - string
                    - 'null'
                  userSearchBase:
                    type:
                    - string
                    - 'null'
                  userSearchFilter:
                    type:
                    - string
                    - 'null'
                  allowedGroups:
                    type:
                    - array
                    - 'null'
                    items:
                      type: object
                      additionalProperties: false
                      properties:
                        name:
                          type: string
                        defaultRoleIds:
                          type: array
                          items:
                            type: integer
                        defaultProfileId:
                          type: integer
                  enableSaslBinding:
                    type: boolean
                  relayId:
                    type:
                    - number
                    - 'null'
                  relayUuid:
                    type:
                    - string
                    - 'null'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      tags:
      - LDAP Configuration
      x-tenablead-required-product-license-type:
      - ioa
      - ioaPreview
      - ioe
      parameters:
      - name: x-api-key
        description: The user's API key
        in: header
        schema:
          type: string
          default: put-your-api-key-here
        required: true
        deprecated: false
      security:
      - ApiKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                enabled:
                  type: boolean
                url:
                  type:
                  - string
                  - 'null'
                searchUserDN:
                  type:
                  - string
                  - 'null'
                searchUserPassword:
                  type:
                  - string
                  - 'null'
                userSearchBase:
                  type:
                  - string
                  - 'null'
                userSearchFilter:
                  type:
                  - string
                  - 'null'
                allowedGroups:
                  type:
                  - array
                  - 'null'
                  minItems: 1
                  items:
                    type: object
                    required:
                    - name
                    - defaultRoleIds
                    - defaultProfileId
                    additionalProperties: false
                    properties:
                      name:
                        type: string
                      defaultRoleIds:
                        type: array
                        items:
                          type: integer
                      defaultProfileId:
                        type: integer
                enableSaslBinding:
                  type: boolean
                relayId:
                  type:
                  - number
                  - 'null'
      operationId: patchApiLdapConfiguration
      x-operation-id-source: derived
components:
  securitySchemes:
    ApiKey:
      name: x-api-key
      description: The user's API key
      in: header
      type: apiKey
x-readme:
  explorer-enabled: true
  proxy-enabled: true
